### ISSUE TITLE
antares python name

### ISSUE THREAD

**Issue by raphaelshirley** [noaodatalab/notebooks-latest#16]
After doing
pip install antares-client
I can do "import antares_client" but not "import antares" meaning the notebook

notebooks-latest/05_Contrib/TimeDomain/AntaresDevKit/AntaresFilterDevKit.ipynb

Does not work.

How should I modify the names?

Best,

Raphael.

**Comment by cstubens** [comment]
Hi @raphaelshirley,

This notebook is designed to run within NOAO's DataLab Jupyter environment.
In the notebook "Summary" section are instructions on how to get started.

Carl

**Comment by rnikutta** [comment]
from @cstubens:

Hi @raphaelshirley,

This notebook is designed to run within NOAO's DataLab Jupyter environment.
In the notebook "Summary" section are instructions on how to get started.

Carl
